### ISSUE TITLE
[Redux] Fail to setup 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-editor#68]
1) README currently says we should run `npm run vendor` which will run `npm install` for us.

However, doing so with vanilla clone give me

```

sh: react-scripts: command not found

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vega-editor-redux@0.1.0 build: `react-scripts build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the vega-editor-redux@0.1.0 build script 'react-scripts build'.
npm ERR! This is most likely a problem with the vega-editor-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get their info via:
npm ERR!     npm owner ls vega-editor-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/npm-debug.log
cp: /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega/build/*: No such file or directory
cp: /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega-embed/vega-embed*: No such file or directory
mkdir: public/vendor: No such file or directory
cp: node_modules/ace-builds/src-min/ace.js: No such file or directory
cp: node_modules/ace-builds/src-min/mode-json.js: No such file or directory
cp: node_modules/ace-builds/src-min/worker-json.js: No such file or directory
cp: node_modules/ace-builds/src-min/ext-searchbox.js: No such file or directory
Copying data to 'public/data'.
mkdir: public: No such file or directory
cp: /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega-datasets/data/*: No such file or directory
Copy examples to 'spec'.
cp: /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega/spec: No such file or directory
cp: /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega-lite/examples/specs: No such file or directory
cat: /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega-lite/examples/vl-examples.json: No such file or directory
./scripts/vendor.sh: line 71: public/js/vl-specs.js: No such file or directory

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "run" "vendor"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! vega-editor-redux@0.1.0 vendor: `./scripts/vendor.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vega-editor-redux@0.1.0 vendor script './scripts/vendor.sh'.
npm ERR! This is most likely a problem with the vega-editor-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/vendor.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls vega-editor-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

2) Even if I tried to install `npm install` first.  I still get a (different) error for `npm run vendor`.

```

> vega@3.0.0-beta.1 pretest /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega
> rm -rf build && mkdir build && bin/rollup && bin/schema > build/vega-schema.json

module.js:339
    throw err;
    ^

Error: Cannot find module 'rollup'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega/bin/rollup:3:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! vega@3.0.0-beta.1 pretest: `rm -rf build && mkdir build && bin/rollup && bin/schema > build/vega-schema.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vega@3.0.0-beta.1 pretest script 'rm -rf build && mkdir build && bin/rollup && bin/schema > build/vega-schema.json'.
npm ERR! This is most likely a problem with the vega package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf build && mkdir build && bin/rollup && bin/schema > build/vega-schema.json
npm ERR! You can get their info via:
npm ERR!     npm owner ls vega
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega/npm-debug.log

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! vega@3.0.0-beta.1 build: `npm run test && uglifyjs build/vega.js -c -m -o build/vega.min.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vega@3.0.0-beta.1 build script 'npm run test && uglifyjs build/vega.js -c -m -o build/vega.min.js'.
npm ERR! This is most likely a problem with the vega package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test && uglifyjs build/vega.js -c -m -o build/vega.min.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls vega
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega/npm-debug.log
cp: /Users/kanitw/Documents/_code/_idl/_visrec/vega-editor/node_modules/vega/build/*: No such file or directory
Copying data to 'public/data'.
Copy examples to 'spec'.
```

**Comment by kanitw** [comment]
@domoritz found that running `npm install` inside `node_modules/vega` helps.  Not sure if this is Vega's problem or this repo's problem.

**Comment by domoritz** [comment]
The instructions in the README have not been updated. The instructions right now are

* npm install
* npm link vega-lite
* cd node_modules/vega
* npm install
* cd ../..
* npm run vendor
* npm start
* pray

**Comment by mathisonian** [comment]
I've updated the build process (and README) so from a fresh clone you just need to do the following:

```
$ npm install
$ npm start
```

I temporarily disabled vega-lite because the `vega/vega-lite#vg3` version doesn't seem to be importing correctly. It is looking for `src/index.js` but the entire `src` folder looks like its not being included during installation for some reason.

**Comment by domoritz** [comment]
If you link vega-lite, things should work correctly. I suspect that things will work correctly when we release vega-lite vis npm properly.
